export default {
  stateList : [
    {v:"AB",n:"Alberta"},
    {v:"AK",n:"Alaska"},
    {v:"AL",n:"Alabama"},
    {v:"AR",n:"Arkansas"},
    {v:"AZ",n:"Arizona"},
    {v:"BC",n:"British Columbia"},
    {v:"CA",n:"California"},
    {v:"CO",n:"Colorado"},
    {v:"CT",n:"Connecticut"},
    {v:"DE",n:"Delaware"},
    {v:"FL",n:"Florida"},
    {v:"GA",n:"Georgia"},
    {v:"HI",n:"Hawaii"},
    {v:"IA",n:"Iowa"},
    {v:"ID",n:"Idaho"},
    {v:"IL",n:"Illinois"},
    {v:"IN",n:"Indiana"},
    {v:"KS",n:"Kansas"},
    {v:"KY",n:"Kentucky"},
    {v:"LA",n:"Louisiana"},
    {v:"MA",n:"Massachusetts"},
    {v:"MB",n:"Manitoba"},
    {v:"MD",n:"Maryland"},
    {v:"ME",n:"Maine"},
    {v:"MI",n:"Michigan"},
    {v:"MN",n:"Minnesota"},
    {v:"MO",n:"Missouri"},
    {v:"MS",n:"Mississippi"},
    {v:"MT",n:"Montana"},
    {v:"NB",n:"New Brunswick"},
    {v:"NC",n:"North Carolina"},
    {v:"ND",n:"North Dakota"},
    {v:"NE",n:"Nebraska"},
    {v:"NF",n:"Newfoundland and Labrador"},
    {v:"NH",n:"New Hampshire"},
    {v:"NJ",n:"New Jersey"},
    {v:"NM",n:"New Mexico"},
    {v:"NS",n:"Nova Scotia"},
    {v:"NT",n:"Northwest Territories"},
    {v:"NU",n:"Nunavut"},
    {v:"NV",n:"Nevada"},
    {v:"NY",n:"New York"},
    {v:"OH",n:"Ohio"},
    {v:"OK",n:"Oklahoma"},
    {v:"ON",n:"Ontario"},
    {v:"OR",n:"Oregon"},
    {v:"PA",n:"Pennsylvania"},
    {v:"PE",n:"Prince Edward Island"},
    {v:"QC",n:"Québec"},
    {v:"RI",n:"Rhode Island"},
    {v:"SC",n:"South Carolina"},
    {v:"SD",n:"South Dakota"},
    {v:"TN",n:"Tennessee"},
    {v:"TX",n:"Texas"},
    {v:"UT",n:"Utah"},
    {v:"VA",n:"Virginia"},
    {v:"VT",n:"Vermont"},
    {v:"WA",n:"Washington"},
    {v:"WI",n:"Wisconsin"},
    {v:"WV",n:"West Virginia"},
    {v:"WY",n:"Wyoming"},
    {v:"YK",n:"Yukon"}
  ],
  neighbors: {
    AB: ['SK','BC','MT','NT'],
    AK: ['BC','YK'],
    AL: ['FL','GA','MS','TN'],
    AR: ['MO','TN','MS','LA','TX','OK'],
    AZ: ['NM','CA','CO','UT','NV'],
    BC: ['WA','ID','MT','AB','YK','AK'],
    CA: ['OR','AZ','NV'],
    CO: ['WY','NE','KS','OK','NM','AZ','UT'],
    CT: ['MA','RI','NY'],
    DE: ['NJ','PA','MD'],
    FL: ['GA','AL'],
    GA: ['NC','SC','FL','AL','TN'],
    HI: [],
    IA: ['IL','MO','MN','NE','WI'],
    ID: ['BC','MT','WY','UT','NV','OR','WA'],
    IL: ['WI','IN','KY','MO','IA'],
    IN: ['MI','OH','KY','IL'],
    KS: ['NE','MO','OK','CO'],
    KY: ['IN','OH','WV','VA','TN','MO','IL'],
    LA: ['TX','AR','MS'],
    MA: ['CT','RI','NY','VT','NH'],
    MB: ['NT','NU','ON','MN','ND','SK'],
    MD: ['DE','VA','WV','PA'],
    ME: ['NB','NH','QC'],
    MI: ['WI','ON','OH','IN'],
    MN: ['IA','ON','MB','WI','SD','ND'],
    MO: ['IA','IL','KY','TN','AR','OK','KS','NE'],
    MS: ['TN','AL','LA','AR'],
    MT: ['AB','SK','ND','SD','WY','ID','BC'],
    NB: ['NS','QC','ME'],
    NC: ['VA','SC','GA','TN'],
    ND: ['SK','MB','MN','SD','MT'],
    NE: ['SD','IA','MO','KS','CO','WY'],
    NF: ['QC'],
    NH: ['ME','VT','MA','QC'],
    NJ: ['PA','NY','DE'],
    NM: ['TX','CO','OK','AZ','UT'],
    NS: ['NB'],
    NT: ['NU','MB','SK','AB','YK'],
    NU: ['NT','MB','SK'],
    NV: ['OR','ID','CA','UT','AZ'],
    NY: ['NJ','ON','VT','MA','CT','PA','QC'],
    OH: ['MI','ON','PA','WV','KY','IN'],
    OK: ['KS','CO','MO','AR','TX','NM'],
    ON: ['QC','NY','OH','MI','MN'],
    OR: ['CA','WA','ID','NV'],
    PA: ['DE','NY','NJ','OH','MD','WV'],
    PE: [],
    QC: ['ON','NF','NB','NH','VT','NY'],
    RI: ['CT','MA'],
    SC: ['NC','GA'],
    SD: ['ND','MN','IA','NE','WY','MT'],
    TN: ['KY','VA','NC','GA','AL','MS','AR','MO'],
    TX: ['OK','AR','LA','NM'],
    UT: ['ID','WY','CO','NM','AZ'],
    VA: ['WV','MD','NC','TN','KY'],
    VT: ['NH','NY','QC','MA'],
    WA: ['BC','ID','OR'],
    WI: ['IA','MN','MI','IL'],
    WV: ['PA','VA','MD','KY','OH'],
    WY: ['MT','SD','NE','CO','UT','ID'],
    YK: ['AK','BC','NT']
  }
}
